version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
